### PR TITLE
Remove usage of Nette\Object class

### PR DESCRIPTION
**Pull request by PavelJurasek**

### CODE REVIEW

**Comment by enumag** [comment]
Very nice. Could you look into the failing tests?

**Comment by PavelJurasek** [comment]
I've been digging into it a bit, but I really can't tell what causes that fields first_name and last_name are missing from the response. It shouldn't be related to this PR anyway.

**Comment by enumag** [comment]
I don't think it's related to this PR. I can certainly merge it as is. But even if I merge it I can't tag a new version for you without the tests passing and I don't have time to fix that.

**Comment by PavelJurasek** [comment]
Tests are green (coverage not so much..). Is it mergeable?

**Comment by enumag** [comment]
Merged, thanks. Next time please ping me if I don't respond for a week.

**Pull request merged**
