### PR TITLE
Facebook: added checkPermissions method

### PR DESCRIPTION
**Pull request by pitrrs**
This method re-checks needed permissions based on configuration.

Basic example:
```php
if (!$this->fb->checkPermissions()){
   $dialog = $this->fb->createDialog("login");
   $loginUrl = $dialog->getUrl(
      $dialog::DISPLAY_PAGE // Or what do you need...
   );
   $this->redirectUrl($loginUrl."&auth_type=rerequest"); // TODO: Add "re-request" type as param
}
```

### CODE REVIEW

**Comment by fprochazka** [comment]
Have you seen https://github.com/Kdyby/Facebook/blob/b4ea4d756b3ba095e635b507fecd8566b306e134/src/Kdyby/Facebook/Profile.php#L130 ?

**Comment by fprochazka** [comment]
I think instead of using it like 

```php
$loginUrl = $dialog->getUrl(
    $dialog::DISPLAY_PAGE // Or what do you need...
);
$this->redirectUrl($loginUrl."&auth_type=rerequest");
```

there should be new method `rerequest()` just like there is `open()` and `handleOpen()`

**Comment by fprochazka** [comment]
Also, I think such workflow is not ideal. You're supposed to try do the action you need to and if the action fails, then you can check the permissions and rerequest them.

You can't relly on the fact, that user allowed you some permissions.. he might have done that by accident and then he went and removed them immediately.. so it's not safe to cache such state.

**Comment by pitrrs** [comment]
Behold, I have not seen it ... You're right, it's a better solution. Method rerequest() would resolve this, I tested with just open(), but Facebook does not display a confirmation dialog again and permissions is therefore not allocated.

**Comment by fprochazka** [comment]
Rerequest is implemented, so I guess this is solved :)

https://github.com/Kdyby/Facebook/pull/30

**Pull request closed without merging**
